/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface MailchimpScenario {
    }
  }

  interface HTMLMailchimpScenarioElement extends StencilComponents.MailchimpScenario, HTMLStencilElement {}

  var HTMLMailchimpScenarioElement: {
    prototype: HTMLMailchimpScenarioElement;
    new (): HTMLMailchimpScenarioElement;
  };
  interface HTMLElementTagNameMap {
    'MailchimpScenario': HTMLMailchimpScenarioElement;
  }
  interface ElementTagNameMap {
    'MailchimpScenario': HTMLMailchimpScenarioElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'MailchimpScenario': JSXElements.MailchimpScenarioAttributes;
    }
  }
  namespace JSXElements {
    export interface MailchimpScenarioAttributes extends HTMLAttributes {
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
